PP-10717: Upgrade Docker Java image
alphagov/pay-cardid pull request #965
Opened 2023-02-20 17:39 UTC by oswaldquek

[Image location](https://hub.docker.com/layers/library/eclipse-temurin/11.0.18_10-jre-alpine/images/sha256-4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad?context=explore).

2023-02-20 18:17 UTC, nlsteers requested changes
Don't forget the ARM64 Dockerfile [here](https://github.com/alphagov/pay-cardid/blob/0934ddbcd9ad7ca003850e84bea747e6f21ff41f/m1/arm64.Dockerfile#LL1)

2023-02-21 09:45 UTC, oswaldquek commented
@nlsteers fixed

2023-02-21 12:03 UTC, oswaldquek commented on dependency-reduced-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
hmm I saw this before, deleted it and now it's back there

2023-02-21 12:04 UTC, oswaldquek commented on dependency-reduced-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
removed

2023-02-21 12:16 UTC, nlsteers approved these changes

2023-02-21 13:14 UTC, merged